[role="Isolated Danger Beacon"]
== Isolated Danger Beacon

---

=== ○ 일반기준

- 고정된 항로의 표지로 산호초 또는 얕은 지역 등에 설치되어 위험을 나타내는 용도로 사용됨
- 입표 모양은 망대형 또는 원주형만 존재하며, 두표 모양은 2개의 구체형태로만 구성됨
- 몸체는 흑색 바탕에 홍색 횡선 조합으로 구성되며 두표 색상은 흑색으로만 구성됨.
- 고립장애입표에 설치되는 등화는 백색이며 Fl(2)의 주기를 가짐.
- 속성 [Height]는 평균해수면에서 구조물 최상단의 높이입력 (등대표상 없는 정보임)
  (속성 [Height]가 S-57전자해도에 존재한다면 확인필요)
- 속성 [Vertical Length]는 지면상 높이에서 구조물 최상단의 높이를 입력 (구조물 자체만의 높이 – 등대표에 제시됨)
  ([Height]가 입력된 경우 대부분 [Vertical length] 정보임)
- 고립장애입표가 Light객체와 함께 입력되어 등표로 표현되는 경우 해당 등대번호는 Light객체에 입력
   (등표로 형성된 경우 등대번호가 고립장애입표에 입력되어 있으면 수정필요)
- 입표와 등화 무신호, 레이더비콘, 라디오비콘 등 입표와 부속된 피처들이 있다면 {Structure/Equipment} 관계 설정
  ※ Relation 페이지 참조
- 입표와 두표의 항행통보 번호가 다를 경우 최신의 항행통보 정보 하나만 입력

---
=== ○ 입력예시

|===

2+^|Attribute ^|Mult. ^|Type ^|Value

2+|Beacon shape ^|1.1 ^|EN |5:pile beacon
2+|Colour ^| 1.* ^|EN | 2:black
2+|Colour ^| 1.* ^|EN | 3:red
2+|Colour ^| 1.* ^|EN | 2:black
2+|Colour pattern ^|0.1 ^|EN | 1:horizontal stripes
2+|Radar conspicuous ^|0.1 ^|BO | false
2+|Visual prominence ^|0.1 ^|EN | 1:visual prominence
2+|Height ^|0.1 ^|RE | 삭제
2+|Nature of construction ^|0.* ^|EN |2:concreted
.3+|Feature name ^|Name usage .3+^|0.* ^|EN |1: default name display
^|Language ^|TE |eng
^|Name ^|TE |Sumeunnyeo
.3+|Feature name ^|Name usage .3+^|0.* ^|EN |2: alternate name display
^|Language ^|TE |kor
^|Name ^|TE |숨은여
2+|Vertical length ^|0.1 ^|RE|5m
.2+|Information ^|Language .2+^|0.* ^|TE |eng
^|Text ^|TE |추가정보(영문)
.2+|Information ^|Language .2+^|0.* ^|TE |kor
^|Text ^|TE |추가정보(국문)
.2+|Topmark ^|Colour ^|0.* ^|EN |2:Black
^|Topmark/day mark shape ^|1.1 ^|EN |4:2 spheres

|===



