// tag::CautionArea[]
===== Remark
* 항해자에게 경고와 알림(Alert and Indication)이 필요한 지역에 한하여 span:F[Caution Area]를 입력
** span:F[Caution Area]는 ECDIS의 경보를 유발하기 때문에 항해자에게 경보를 통한 경각심이 필요한 경우에 한하여 입력해야 함
* 다음과 같은 사항에 span:F[Information Area]를 입력
** 항해자에게 유용할 수는 있으나, 안전한 항해와 명백한 관계가 없는 사항
** 항해자와 관련이 있으나 ECDIS 경보를 울릴 필요가 없는 주의구역 정보
* 종이해도에 주의기사를 입력할 때에는 항해안전을 위한 정보 제공 목적인지, 일반 정보 제공 목적인지 구분해야 하여 span:F[Caution Area] 또는 span:F[Information Area]로 입력해야 함 +
또한, 셀 구역 전체에 입력하는 것을 피해야함

//
* 입력 조건

** 공사중, 매립중
*** 공사 기간, 공사 도면 등을 입수 했다면 해당 객체(예 : span:F[Shoreline Construction] 등)에 span:A[information] 또는 span:F[Nautical Information] 으로 입력해야 함
*** 그 외의 경우 측량원도에 표기된 공사중, 매립중은 자세한 정보가 입수 될 때까지 span:F[Caution Area]로 입력해야 함
*** 공사중인 영역의 span:F[Caution Area]은 span:A[condition] = 1 span:d[under construction]으로만 입력하고, span:A[information/text] = (Under Construction) 또는 (공사중) 과 같이 입력하지 않아야 함
*** 매립중인 영역의 span:F[Caution Area]은 span:A[condition] = 3 span:d[under reclamation]으로만 입력하고, span:A[information/text] = (Under Reclamation) 또는 (매립중) 과 같이 입력하지 않아야 함

** 미측 구역 
*** span:F[Unsurveyed Area]와 중첩하여 span:F[Caution Area][P,S]로 입력해야 함
*** span:F[Caution Area][S]는 span:F[Depth Contour]와 같이 화면 표시 우선 순위 (Display Priority) 3 이상의 객체와 중첩하면 안되며, 이 경우 span:F[Data Coverage]에 입력된 span:A[optimum display scale]에 해당하는 화면 축척으로 최소 0.3mm(도상거리) 이상 span:F[Caution Area]를 더 크게 그려줘야 함

** 송전선
*** span:F[Cable Overhead]를 따라 span:F[Caution Area][C]로 입력하지 않아야 함
*** span:F[Data Coverage]에 입력된 span:A[optimum display scale]에 해당하는 화면 축척으로 최소 0.3mm(도상거리) 이상 (양쪽으로 입력해야 하므로 총 0.6mm 이상)의 얇은 면을 해당 송전선을 따라 span:F[Caution Area][S] 로 입력해야 함

** 안벽
*** 안벽에 대한 수심 이격거리가 지정된 항만 또는 부두 안벽에는 실제 이격 거리만큼의 폭으로 span:F[Caution Area][S]를 해당 안벽 선을 따라 바다 방향으로 입력해야 함
**** span:F[Caution Area][S] 내부에는 span:F[Sounding]를 입력하지 않아야 함
*** 그 외 항행 주의 사항은 span:F[Data Coverage]에 입력된 span:A[optimum display scale]에 해당하는 화면 축척에서 span:F[Caution Area][S]를 생성
*** 이때 최소 0.3mm(도상거리)의 얇은 면(surface)을 해당 안벽 선을 따라 바다 방향으로 생성해야 함.
*** 안벽에 대한 일반정보는 span:F[Information Area]로 입력

** 암초
*** 해당 객체 주변에 span:F[Caution Area][P,S]를 입력 (셀 구역 전체에 입력된 span:F[Caution Area]를 삭제)
*** 필요하면 해당 객체 주변에 span:F[Caution Area] 보다 span:F[Obstruction][S] 를 입력하여 위험계선을 생성하는 것을 권장

** 기타 사례
*** 관련 기사 : 항해주의, 잠수정, 선박횡단, 고도제한, 사주, 사퇴, 모래톱, 좌주, 토사 등
*** 대상 객체 주변에 span:F[Caution Area][P,C,S]를 입력하고 span:A[information]또는 span:F[Nautical Information] 관련 정보를 입력

* 위에 언급되지 않은 난외 기사는 관련 객체 또는 span:F[Information Area]에 입력

* span:A[fixed date range]의 하위 속성 span:A[date end]의 날짜가 지난 경우, span:F[Caution Area]는 삭제해야 함

===== Example
.Caution Area의 인코딩 예시
[cols="30,25,10,10,25", options="header"]
|===
|Attribute |Acronym |Type |Mult. |Value

|**information**|INFORM|C|0,*|
|    span:E[language]||(S)TE|1,1|eng
|    text|INFORM/NINFOM|(S)TE|0,1|The overhead power cable spanning the YEONGHEUNG SUDO is widened unusually on the radar scope, so mariners are required to navigate with caution in this area.
|**information**|INFORM|C|0,*|
|    span:E[language]||(S)TE|1,1|kor
|    text|INFORM/NINFOM|(S)TE|0,1|영흥수도 위를 횡단하는 송전선은 레이더 화면에 비정상적으로 확대되어 보이므로 이 수도를 항해하는 선박은 주의하여야 함.
|===

---
// end::CautionArea[]
