// tag::DeepWaterRoutePart[]
===== Remark

* span:F[Deep Water Route Part]은 깊은 수심 항로를 면(Surface)형태로 입력할때 사용
* 깊은 수심 항로의 이름을 표시할 때는 span:R[Deep Water Route Aggregation] 관계의 span:F[Deep Water Route]의 span:A[feature name] 에 입력
** 만약 깊은 수심 항로가 단순해서 span:F[Deep Water Route Part] 하나로 전체 항로를 나타낼 수 있다면 해당 객체의 span:A[feature name] 에 입력

//
* span:A[depth range minimum value]는 필수이며 항로 내 최소 수심 값을 입력
** 단, span:F[Deep Water Route Part]는 span:F[Dredged Area]와 달리 항만청이나 항만공사의 직접적인 관리 없이 연안 해역에 주로 지정되어 최소 수심이 완전히 보장되지 않으므로, +
수로국이 특정 span:F[Deep Water Route]내 최소 수심을 확실히 보장할 수 있다면, span:A[depth range minimum value] 속성에 이 값을 입력해야 함

//
* 굽이진 경로로 구성된 깊은 수심 항로는, 각 구간을 별도로 분리하여 각각의 span:F[Deep Water Route Part]에 대해 span:A[orientation value]를 입력해야 함
* span:A[orientation value]는 필수이며 일방통행* 일때는 선박이 진행하는 방향으로 방위각을 입력하고, 양방향일때는 180 미만의 값을 입력해야 함
** 일방통행 : span:A[traffic flow] = (1 : inbound, 2 : outbound or 3 : one-way)

//
* 법령 및 고시 등에 깊은 수심 항로 내 제한 속력이 명시되어 있거나, 별도의 속력 제한 구역의 범위가 일치하면 span:F[Restricted Area]를 별도로 입력하지 않고 span:F[Deep Water Route Part]에 span:A[vessel speed limit]를 직접 입력

//
* span:F[Deep Water Route Part]가 span:R[Deep Water Route Aggregation] 또는 span:R[Traffic separation scheme Aggregation] 에 포함된 경우 span:A[IMO adopted]를 입력해서는 안됨
** IMO가 지정한 깊은 수심 항로는 IMO 간행물 "Ships' Routeing" Part C 참고

===== Example
.Deep Water Route Part의 인코딩 예시
[cols="30,25,10,10,25", options="header"]
|===
|Attribute |Acronym |Type |Mult. |Value

|span:E[depth range minimum value]|DRVAL1|RE|1,1| 30
|span:E[orientation value]|ORIENT|RE|1,1| 139
|span:E[traffic flow]|TRAFIC|EN|1,1|3
|===

---
// end::DeepWaterRoutePart[]
