// tag::DepthArea[]
===== Remark

* span:F[Depth Area]는 span:F[Dredged Area], span:F[Unsurveyed Area], span:F[Land Area]와 함께 **Skin of the Earth**에 포함되는 객체 중 하나임
* 항해가 가능한 수역(바다, 강, 호수, 운하, 선거 등)은 특정 깊이 범위를 가지는 span:F[Depth Area]로 분리해야 함
** 각 span:F[Depth Area]에 대해 span:A[depth range minimum value]와 span:A[depth range maximum value]는 필수이며 해당 영역의 가장 얕은 깊이와 가장 깊은 깊이에 해당하는 값으로 입력해야 함
** 가장 얕은 영역과 가장 깊은 영역을 제외하고, 이러한 값은 데이터 셋에 입력된 span:F[Depth Contour]의 값에서 선택해야 함
* 알려진 수역의 이름은 span:F[Sea Area/Named Water Area]를 사용하여 입력해야 함

//
* 강, 호수, 운하, 선거를 span:A[optimum display scale]에 해당하는 화면 축척에서 항해가 가능한 경우 span:F[Depth Area] 또는 span:F[Dredged Area]로 입력하고 +
그 경계는 span:F[Coastline] 또는 span:F[Shoreline Construction]로 입력해야 함
** 이러한 영역의 이름을 입력해야 하는 경우, span:F[Sea Area/Named Water Area] 로 입력

//
* 전자해도에 약최고고조면을 입력할 때 span:F[Depth Area]의 span:A[depth range minimum value]는 **-H** 를 계산하여 입력.
* **-H** 값은 최신 조석표를 기준으로 셀에서 가장 가까운 위치의 평균해면(Z~0~) 값을 2배로 한 후, (-) 부호를 붙여 산정
* 셀 내에 두 개 이상의 관측소가 있는 경우, 평균해면(Z~0~) 값 중 가장 큰 값을 사용하여 **-H** 를 계산하고 셀 내에서는 같은 값을 입력
* **-H** 값은 소수 첫째 자리까지 반올림하여 입력
* **-H** 값보다 낮은 수심이 있는 경우
** 과업구역 내 : 수로측량 시행처 문의를 통해 노출암 변경사항을 검토
** 과업구역 외 : 전자해도 제작 시 해당 객체의 span:A[exposition of sounding] 에 (2 : shoaler than the range of depth of the surrounding depth area)입력
* span:A[depth range minimum value]는 -30m 보다 얕을 수 없고, 12500m 보다 깊을 수 없음
** -30 < span:A[depth range minimum value] < 12500
* span:A[depth range maximum value] 는 -30m 보다 얕을 수 없고, 12500m 보다 깊을 수 없음
** -30 < span:A[depth range maximum value] < 12500

//
include::common/information.adoc[]

===== Example
.Depth Area의 인코딩 예시
[cols="30,25,10,10,25", options="header"]
|===
|Attribute |Acronym |Type |Mult. |Value

|span:E[depth range minimum value]|DRVAL1|RE|1,1| -4.7
|span:E[depth range maximum value]|DRVAL2|RE|1,1| 0

|===

---
// end::DepthArea[]
