// tag::Dolphin[]
===== Remark
- S-57 전자해도의 속성 #A "CATMOR"에 따라 매칭되는 피처 및 속성은 아래의 표를 참조하여 인코딩

[%header,cols="1,1,4",format=csv]
|===
S-57 CATMOR,S-101 Feature,S-101 Attribute
1(dolphin),Dolphin,[Category of dolphin] = 1(mooring dolphin)
2 (deviation dolphin),Dolphin,[Category of dolphin] = 2(deviation dolphin)
3 (bollard),Bollard,
4 (tie-up wall),Shoreline Construction,[Category of shoreline construction] = 23(tie-up wall)
5 (post of pile),Pile,[Category of pile] = 8(mooring post)
6 (chain/wire/cable),Cable Submarine,[Category of cable] = 9(junction cable)
7 (mooring buoy),Mooring Buoy,
|===

- #F "Dolphin"은 Line type으로 입력이 불가능하므로 S-57 전자해도에서 Line type으로 입력된 경우 인코딩 기준 확인
- 항해 위험이 될 수 있는 사용되지 않는 계류/계선시설 또는 잔해는 #F "Obstruction" 피처로 인코딩하며 #A "Category of obstruction" = 1(snag/stump)로 입력
- 사용하지 않는 계류/계선시설 또는 잔해는 “Pile” 피처로 인코딩하며 #A "Category of pile" = 8(mooring post), #A "condition" = 2(ruined)로 입력

===== Example
[cols="30,25,10,10,25", options="header"]
|===
|Attribute |Acronym |Type |Mult. |Value

|#essential Category of Dolphin||EN|1,*| 1: mooring dolphin
|===
1
---
// end::Dolphin[]
