// tag::DumpingGround[]
===== Remark

* 바다에 의도적으로 자재(매립 공사와 관련된 것을 제외)가 투기되는 지정된 지역은 항해자에게 미치는 중요도에 따라 다음과 같이 분류될 수 있음
** 해저면에 도달하기 전에 일반적으로 분산되는 자재(예: 하수 슬러지)는 항해에 거의 영향을 미치지 않으며, 보통 전자해도에 입력이 필요하지 않음
** 준설 공사 구역에서 나오는 준설토가 지정된 투기장에서 해도에 표기된 수심을 크게 감소시킬 가능성이 있는 경우 입력해야 함
** 폐기된 폭발물 및 화학물질을 포함한 유해 물질로, 해저면에 집중적으로 남아 있을 가능성이 있는 경우 입력해야 함. 다만, 유해 물질의 투기는 수심에 큰 영향을 미치지 않을 가능성이 높으며, 이러한 투기장은 주로 닻 내리기, 트롤 어업, 또는 기타 수중 작업에 대한 경고로 입력

//
* span:F[Dumping Ground]은 span:F[Depth Area] 또는 span:F[Unsurveyed Area]로 덮여야 함
* 준설 공사 구역(Dredging Area)에서 얻은 자재를 처분하기 위한 준설토 투기장은 span:F[Dumping Ground]에 span:A[category of dumping ground] = (5 :spoil ground)로 입력
* 준설 공사 구역(Dredging Area)는 span:F[Dredged Area]와 혼동하지 않아야 하며, 필요한 경우 span:F[Restricted Area]에 span:A[category of restricted area] = (27 :dredging area)로 입력
* 건설 등 목적으로 모래, 자갈과 같은 해저 자재를 추출하는 지역은 필요한 경우 span:F[Offshore Production Area]에 span:A[category of offshore production area] = (5 : seabed material extraction area)로 입력

//
* 유해 물질을 위한 투기장은 사용이 중지되었더라도 무기한 위험한 것으로 간주되며, span:A[status] = (4 : not in use)와 함께 대축척 전자해도부터 입력되어야 함. 
* 해당 구역이 사용되지 않게 된 날짜가 알려진 경우 span:A[date disused]를 사용하여 입력

//
* span:F[Dumping Ground]에 자재 투기 후 수심이 해도에 표기된 수심보다 훨씬 얕아질 가능성이 있고 투기 후 측량 결과가 없으면, 해당 지역은 span:F[Unsurveyed Area]로 입력할 수도 있으며, 이 경우 해당 구역에서 span:F[Sounding]과 span:F[Depth Contour]를 생략할 수 있음
** 대안으로, 해도에 표기된 수심과 span:F[Dumping Ground] 구역 내 실제 수심 간의 차이를 나타내기 위해 span:F[Quality of Bathymetric Data]에 포함된 정보를 낮추는(degrading) 방식으로 입력할 수도 있음

//
* 법령 및 고시 등에 투기장 내 제한 속력이 명시되어 있거나, 별도의 속력 제한 구역의 범위가 일치하면 span:F[Restricted Area]를 별도로 입력하지 않고 span:F[Dumping Ground]에 span:A[vessel speed limit]를 직접 입력

===== Example
.Dumping Ground의 인코딩 예시
[cols="30,25,10,10,25", options="header"]
|===
|Attribute |Acronym |Type |Mult. |Value

|category of dumping ground|CATDPG|EN|0,*| 4 : explosives dumping ground
|status|STATUS|EN|0,*| 4 : not in used
|===
---
// end::DumpingGround[]
