// tag::TrafficSeparationScheme[]
===== Remark
* 통항분리제도가 적용되는 수역은 span:F[Traffic Separation Scheme]으로 입력
** 명칭이 없는 경우에는 NoGeometry 형태로 입력해도 무방 span:D[법령에 의해 정해진 경우 명칭이 있으므로, 가급적 NoGeometry는 사용하지 않음]
** 명칭이 있는 경우, 명칭은 span:A[feature name]으로 입력하고, span:F[Traffic Separation Scheme]은 **Surface**형태로 입력해야 함 +
   _(이 때, 지오메트리는 통항분리제도를 이루는 모든 구성 요소를 포함할 수 있도록 입력)_
** 통항분리제도가 적용되는 수역이 맏닿아 있더라도, 구분되는(명칭이 서로 다른) 경우 각각 별개로 입력해야 함

//
* span:F[Traffic Separation Scheme]은 다른 구성요소와 span:R[Traffic Separation Scheme Aggregation] 관계를 가져야 함 (<<TSS_AGGR,※참고>>)

//REVIEW: 리뷰 필요
// * span:A[IMO adopted]는 IMO 지정항로 여부를 입력하며, 국내에서는 “해상교통안전법 시행규칙 [별표 20]통항분리방식이 적용되는 수역”에 해당하는 “홍도항로, 보길도항로, 거문도항로”만 span:A[IMO adopted] = true로 입력하고 이 외에는 false로 입력
* span:A[IMO adopted]는 통항분리제도가 국제해사기구(IMO)에 의해 채택되었다면 true, 아니면 false로 입력 span:D[채택여부는 IMO에서 간행하는 Ship's Routeing을 참고한다.]
** 국내에는 통항분리제도가 적용되는 수역이 3곳(홍도항로,보길도항로,거문도항로) 있지만, 모두 채택되어 있는 상태가 아니므로 false로 입력

===== Example
.Traffic Separation Scheme의 인코딩 예시
[cols="30,25,10,10,25", options="header"]
|===
|Attribute |Acronym |Type |Mult. |Value

|IMO adopted|CATTSS|BO|0,1| false
|**feature name**||C|0,*| 
|    span:E[language]||(S)TE|1,1| eng
|    span:E[name]|OBJNAM/NOBJNM|(S)TE|1,1| Masan Fairway
|    name usage||(S)EN|0,1| 1 : _(default name display)_
|**feature name**||C|0,*| 
|    span:E[language]||(S)TE|1,1| kor
|    span:E[name]|OBJNAM/NOBJNM|(S)TE|1,1| 마산항로
|    name usage||(S)EN|0,1| 2 : _(alternate name display)_

|===

---
// end::TrafficSeparationScheme[]


NOTE:
IMO adopted에 관한 설명으로 "해상교통안전법 시행규칙 [별표 20]통항분리방식이 적용되는 수역" ~~ 이라고 적혀 있지만, 해상교통안전법의 75조는 아래와 같다.

[,text]
해상교통안전법 제75조(통항분리제도)
① 이 조는 다음 각 호의 수역(이하 “통항분리수역”이라 한다)에 대하여 적용한다.
1. 국제해사기구가 채택하여 통항분리제도가 적용되는 수역
2. 해상교통량이 아주 많아 충돌사고 발생의 위험성이 있어 통항분리제도를 적용할 필요성이 있는 수역으로서 해양수산부령으로 정하는 수역


현행 지침의 해상교통안전법 시행규칙 [별표 20]은 법 제75조 1항 2호에 해당하는 것으로, 1호 - 국제해사기구(IMO)가 *채택*하여 통항분리제도가 적용되는 것이 아님을 알 수 있다.

따라서 해당 문구를 삭제하고, 별도의 지침이 없는 한 false로 입력한다로 바꾸는 것이 적절한 것으로 판단된다.