// tag::UpdateInformation[]
===== Remark
* S-100 ECDIS에서는 ENC 업데이트 적용 시 시스템 데이터베이스에서 변경된 정보를 항해자의 선택에 따라 시각적으로 표시하도록 구현됨
* span:F[Update Information]은 ENC 신규 판(New Edition)에서 적용된 변경 사항을 항해자에게 알리거나, ENC 업데이트 적용 시 **시각적 표시** 외의 추가 정보를 제공하는 데 사용될 수 있음. 
* span:F[Update Information]이 입력된 경우, 변경된 객체와 함께 span:R[Updated Information] 및 span:R[Update Aggregation]을 통해 반드시 관계가 맺어져야 함

//
* span:A[update number]는 업데이트 데이터셋의 파일 확장자에 표시된 업데이트 번호를 나타내기 위해 반드시 사용해야 함.
** 예 : 해당 업데이트가 포함되어 이번 주에 나갈 데이터셋 버전이 **3**이라면 **3**을 입력
* span:A[update type]은 객체에 적용된 업데이트 유형(삽입, 삭제, 수정, 이동)을 나타내기 위해 반드시 사용해야 함. 
* 다수의 변경이 발생한 영역(예: New Edition)을 커버하도록 span:F[Update Information]이 입력된 경우, span:A[update type] = (3 : modify)으로 입력해야 함
* span:A[information]은 ENC 업데이트에 연관된 객체의 변경 사항에 대한 설명을 제공하는 데 사용해야 함
* ENC 업데이트를 통해 선(Curve) 객체의 **선분(Segment)** 또는 면(Surface) 객체의 **경계(Boundary)**가 옮겨지는 과정은 원래 위치에서 선분(또는 경계)을 삭제하고 새 위치에 새 선분(또는 경계)을 삽입하는 두 단계로 적용해야 함. 
** 필요 시 ENC 업데이트로 선분의 이동을 나타내기 위해, 다음 세 가지 span:F[Update Information]을 생성하고 연관시켜야 함:

1. 원래 위치에서 삭제된 선분의 지리적 형상(geometry)을 사용하며 span:A[update type] = (2 : delete)인 span:F[Update Information]
2. 새 위치에 삽입된 선분과 연관된 선(Curve) 형태의 span:A[update type] = (1 : insert)인 span:F[Update Information]
3. 지리적 형상이 없고(None) span:A[update type] = (4 : move)이며, 위의 "삭제" 및 "삽입" span:F[Update Information] 과 span:R[Update Aggregation]을 통해 연관된 span:F[Update Information]

* span:R[Update Aggregation]은 routeing measure나 range system과 같은 여러 관련 업데이트를 그룹화하는 데 사용할 수 있음. 이 경우, 관계의 집합(container) 역할을 하는 span:F[Update Information]은 지리적 형상이 없고(None) span:A[update type] = (3 : modify)로 입력해야 함.

//
* 변경된 정보가 정보 유형(Information Type)과 관련된 경우, span:F[Update Information]은 해당 정보 유형이 연관된 객체와 연계될 수 있음.

//
* span:A[source]는 관련 종이 해도의 항행통보(Notice to Mariners) 번호를 나타내는 데 사용할 수 있음.

//
* ENC 셀의 각 개정판(New Edition)에서 더 이상 관련 없는 span:F[Update Information]은 반드시 삭제해야 함. 또한 다음 ENC 셀 업데이트에서는 이전 업데이트 데이터셋에 포함된 span:F[Update Information]을 삭제 대상으로 검토해야 함
* 새로운 업데이트가 이전에 업데이트된 객체에 영향을 미치는 경우, 해당 객체와 연관된 기존 span:F[Update Information]은 데이터 셋에서 반드시 삭제해야 함

===== Example

[WARNING]
====
자세한 인코딩 지침은 준비 중 입니다.
====

---
// end::UpdateInformation[]
